# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0003_remove_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Gapp.Category'),
            preserve_default=False,
        ),
    ]
