# Generated by Django 2.0.6 on 2018-06-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0004_articles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='announcer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='activityname',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='deperturevenue',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
